### PR TITLE
Add Color info

### PR DESCRIPTION
**Pull request by jamesmontemagno**
This repo is maintained by the .NET authors. Please submit PRs to contribute your own designs and artwork to the community via the .NET Foundation swag repo here: [dotnet-foundation/swag](https://github.com/dotnet-foundation/swag).

### CODE REVIEW

**Comment by BethMassi** [comment]
There is a color palette in the guidelines and there are more colors than just the purple that can be used in branding elements. I think you're suggesting we put the LOGO color hex value for easy access? I think it would make more sense to create a readme in the Logo folder that has this, or not create a new section but list the hex value in the logo section.

**Comment by jamesmontemagno** [comment]
Yeah, I just want to easily be able to copy and paste the official purple color to use in decks and blogs, etc.  For example -> https://github.com/dotnet-foundation/swag/tree/master/xamarin#colors

**Comment by BethMassi** [comment]
Okay then let's put a sentence "The .NET logo purple color is #512bd4" up to the Logo section since there are more colors in the palette in the guidelines.

**Comment by jamesmontemagno** [comment]
updated

**Comment by BethMassi** [comment]
Thanks!

**Pull request merged**
